version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Zoreman
  - cova
  - procfile
  - deinit
  - sigaction
  - sigset
  - callconv
  - anytype
  - subcmds
  - procs
  - comptime
  - errdefer
  - pgid
  - usize
  - dotenv
import: []
