name: Code Quality
on:
  push:
    branches:
      - master

jobs:
  trunk-code-quality:
    name: Trunk Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
