name: Trunk Upgrade
on:
  schedule:
    - cron: 0 2 * * 2
  workflow_dispatch: {}
permissions: read-all
jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          base: master
